[project]
name = "pythonairesume"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "google-genai>=1.28.0",
    "openai>=1.98.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
]
